Optimize ltsp and common/ltsp

diff --git a/ltsp/ltsp b/ltsp/ltsp
--- a/ltsp/ltsp
+++ b/ltsp/ltsp
@@ -3,14 +3,16 @@
 # Copyright 2019 the LTSP team, see AUTHORS
 # SPDX-License-Identifier: GPL-3.0-or-later
 
-# Main entry point for all ltsp applets
+# Main entry point for all ltsp applets; also contains the essential functions
+
 # Execution sequence:
 # This main() > source common/ltsp/* (and config/vendor overrides)
 # > ltsp_cmdline() > ltsp/scriptname_main()s > source applet/* (and overrides)
 # > applet_cmdline() > applet/scriptname_main()s
 main() {
-    # Always stop on unhandled errors, http://fvue.nl/wiki/Bash:_Error_handling
-    # Prefer `false || false` as it exits while `false && false` doesn't
+    # Try to stop on unhandled errors, http://fvue.nl/wiki/Bash:_Error_handling
+    # Prefer `false || false` as it exits while `false && false` doesn't,
+    # except if it's the last command of a function (return value).
     set -e
 
     re busybox_fallbacks
@@ -23,12 +25,14 @@ main() {
         unset _SOURCED
         # Default to a sane umask for all files generated by applets
         umask 0022
+        # Default to a sane LANG; e.g. python doesn't like unset/C
+        test "${LANG:-C}" != "C" || export LANG=C.UTF-8
     else
         for _LTSP_DIR in "${LTSP_DIR:-/usr/share/ltsp}" "$(re pwd)"; do
             if [ -x "$_LTSP_DIR/ltsp" ] && [ -d "$_LTSP_DIR/common" ]; then
                 _SOURCED=1
                 debug "$_LTSP_DIR/ltsp sourced by $0"
-                # Ignore all the caller command line parameters; they're not for us
+                # Ignore the caller command line parameters; they're not for us
                 set --
                 break
              fi
@@ -52,8 +56,8 @@ at_exit() {
         eval "$_TERM_COMMANDS"
     fi
     eval "$_EXIT_COMMANDS"
-    # It's possible to manually call at_exit, run the commands, then
-    # call exit_command again (e.g. `ltsp kernel img1 img2`).
+    # It's possible to manually call at_exit, run the commands,
+    # then call exit_command again (e.g. for `ltsp kernel img1 img2`).
     unset _TERM_COMMANDS
     unset _EXIT_COMMANDS
     unset _HAVE_TRAP
@@ -64,9 +68,14 @@ at_exit() {
 # if some tool doesn't exist, create a namesake function that calls busybox.
 # `/usr/lib/initramfs-tools/bin/busybox` shows the smallest list of tools.
 busybox_fallbacks() {
-    local tool
+    local busybox tool
 
-    if ! is_command busybox; then
+    busybox=$(command -v busybox)
+    # Ubuntu chroots ship with a "busybox-initramfs" minimal package
+    if [ -z "$busybox" ] && [ -x /usr/lib/initramfs-tools/bin/busybox ]; then
+        busybox=/usr/lib/initramfs-tools/bin/busybox
+    fi
+    if [ -z "$busybox" ]; then
         warn "Busybox not found?!"
         return 0
     fi
@@ -82,65 +91,57 @@ busybox_fallbacks() {
         # applets to see if we are indeed compatible with the busybox syntax
         ! is_command "$tool" || continue
         eval "$tool() {
-    busybox $tool \"\$@\"
+    $busybox $tool \"\$@\"
 }"
     done
 }
 
-# Print a message to stderr if $LTSP_DEBUG is appropriately set
-# TODO: stderr might be redirected; if LTSP_DEBUG is set, backup stderr to
-# stddebug (e.g. #5) initially, then redirect to it here.
+# Show a message to stderr and /run/ltsp/debug.log if $LTSP_DEBUG is
+# appropriately set
 debug() {
     case ",$LTSP_DEBUG," in
-        *",$_APPLET,"*|,1,|,true,)  ;;
+        *",$_APPLET,"*|,1,)  ;;
         *)  return 0;
     esac
-    warn "LTSP_DEBUG:" "$@"
+    warn  "$@"
 }
 
+# The debug shell is used to examine the internals of the ltsp scripts;
+# to get or set variables; so, use `eval`, not `bash`.
 debug_shell() {
-    local setsid
+    local cmd
+    echo "${*:-"Emulating a shell, type \`return [0|1]\` to continue|exit:"}"
 
-    # TODO: make this "repeat y/n" for security reasons, unless some
-    # cmdline parameter is set. Also, check if stdin is valid (| pipe).
-    ( umask 0077; set > /tmp/ltsp-env )
-    warn "${*:-Dropping to a shell for troubleshooting, type exit to continue:}"
-    # Debian defaults to SPLASH="true" and only disables it when
-    # nosplash*|plymouth.enable=0 is passed in the cmdline
-    if [ "$_APPLET" = "initrd-bottom" ] || [ "$_APPLET" = "init" ]; then
-        if [ -x /bin/plymouth ] && pidof plymouthd >/dev/null; then
-            warn "Stopping plymouth"
-            rw plymouth quit
-        fi
-    fi
-    # Use `setsid -c` to enable job control in the shell
-    # `id` isn't available in initramfs, check for root with test -w /
-    if test -w / && is_command setsid; then
-        # TODO: this breaks Ctrl+C for server-side invocations;
-        # temporarily disabled
-        true setsid="setsid -c"
-    else
-        unset setsid
-    fi
-    if is_command bash; then
-        # If the last user command returns false, we fail/exit on purpose!
-        $setsid bash
-    else
-        $setsid sh
-    fi
+    printf "debug:$(pwd)\$ "
+    while read -r cmd; do
+        eval "$cmd" || true
+        printf "debug:$(pwd)\$ "
+    done
 }
 
 # Print a message to stderr and exit with an error code.
 # No need to pass a message if the failed command displays the error.
 die() {
-    if [ $# -eq 0 ]; then
-        warn "Aborting ltsp"
+    test $# -eq 0 && set "Aborting ltsp"
+    # Debian defaults to SPLASH="true" and only disables it when
+    # nosplash*|plymouth.enable=0 is passed in the cmdline
+    if [ "$_APPLET" = "initrd-bottom" ] || [ "$_APPLET" = "init" ]; then
+        if is_command plymouth && pidof plymouthd >/dev/null; then
+            warn "Stopping plymouth"
+            rw plymouth quit
+        fi
+        warn "$@"
+        if [ "$DEBUG_SHELL" != "1" ]; then
+            warn "LTSP boot error! Enable DEBUG_SHELL to troubleshoot!"
+            while sleep 1000; do
+                true
+            done
+            return 0
+        fi
     else
         warn "$@"
     fi
-    if [ "$_APPLET" = "initrd-bottom" ] || [ "$_APPLET" = "init" ]; then
-        debug_shell
-    fi
+    test "$DEBUG_SHELL" = "1" && debug_shell
     # This notifies at_exit() to execute TERM_COMMANDS
     _DIED=1
     # If called from subshells, this just exits the subshell
@@ -154,7 +155,7 @@ echo() {
     printf "%s\n" "$*"
 }
 
-# You may use `at_exit "rw command"`, but not `at_exit "re command"`
+# You may use `exit_command "rw command"`, but not `exit_command "re command"`
 exit_command() {
     if [ "$_HAVE_TRAP" != "1" ]; then
         _HAVE_TRAP=1
@@ -260,7 +261,6 @@ EOF
 # The first column is an increasing directory index.
 # Then sort them in reverse order, and finally by file name,
 # so that "--unique" keeps the last occurrence.
-# TODO: find can be replaced with `for x in $glob`, if needed for dracut
 run_parts_list() {
     local param1 param2 tab i d f
 
@@ -356,9 +356,22 @@ version() {
     echo "ltsp $_VERSION"
 }
 
-# Print a message to stderr
+# Print a message to stderr and log it to /run/ltsp/debug.log
 warn() {
     echo "$@" >&2
+
+    if [ -z "$DEBUG_LOG" ]; then
+        DEBUG_LOG=0
+        # Only keep the last `ltsp command` log for non-ltsp boots
+        test -d /run/ltsp/client || rs rm -f /run/ltsp/debug.log
+        test -w /run &&
+            mkdir -p /run/ltsp &&
+            ( umask 0077 && touch /run/ltsp/debug.log ) &&
+            DEBUG_LOG=1
+    fi
+    if [ "$DEBUG_LOG" = "1" ]; then
+        echo "$(date +%H:%M:%S.%N) $*" >>/run/ltsp/debug.log
+    fi
 }
 
 main "$@"
