Support sourcing ltsp; update client-test.conf

diff --git a/ltsp/ltsp b/ltsp/ltsp
--- a/ltsp/ltsp
+++ b/ltsp/ltsp
@@ -16,20 +16,23 @@ main() {
     # Usually this script is called from a symlink like /usr/sbin/ltsp,
     # so $0 points to the ltsp source directory. If that's not the case,
     # assume we're sourced, and search for the source in /usr/share/ltsp.
-    _LTSP_DIR=$(re readlink -f "$0")
+    _LTSP_DIR=$(re readlink -f "$(command -v "$0")")
     _LTSP_DIR=${_LTSP_DIR%/*}
     if [ -x "$_LTSP_DIR/ltsp" ] && [ -d "$_LTSP_DIR/common" ]; then
         unset _SOURCED
         # Default to a sane umask for all files generated by applets
         umask 0022
-    elif [ -x /usr/share/ltsp/ltsp ] && [ -d /usr/share/ltsp/common ]; then
-        _SOURCED=1
-        debug "ltsp sourced by $0"
-        # Ignore all the caller command line parameters; they're not for us
-        set --
-        _LTSP_DIR=/usr/share/ltsp
     else
-        die "Could not locate the ltsp directory"
+        for _LTSP_DIR in "${LTSP_DIR:-/usr/share/ltsp}" "$(re pwd)"; do
+            if [ -x "$_LTSP_DIR/ltsp" ] && [ -d "$_LTSP_DIR/common" ]; then
+                _SOURCED=1
+                debug "$_LTSP_DIR/ltsp sourced by $0"
+                # Ignore all the caller command line parameters; they're not for us
+                set --
+                break
+             fi
+        done
+        test "$_SOURCED" = "1" || die "Could not locate the ltsp directory"
     fi
     locate_applet_scripts "ltsp"
     source_scripts "$_SCRIPTS"
@@ -54,11 +57,6 @@ at_exit() {
     unset _EXIT_COMMANDS
     unset _HAVE_TRAP
     set -e
-}
-
-# True if can chroot into this dir
-can_chroot() {
-    chroot "$1" true 2>/dev/null || return 1
 }
 
 # Print a message to stderr if $LTSP_DEBUG is appropriately set
@@ -144,45 +142,6 @@ $_EXIT_COMMANDS"
     fi
 }
 
-install_template() {
-    local backup src dst sedp dstdir sname sext language
-
-    if [ "$1" = "-b" ]; then
-        backup=1
-        shift
-    else
-        backup=
-    fi
-    src=$1
-    dst=$2
-    sedp=$3
-    if [ -e "$dst" ] && [ "$OVERWRITE" != "1" ]; then
-        die "Configuration file already exists: $dst
-To overwrite it, run: ltsp --overwrite $_APPLET ..."
-    fi
-    dstdir=${dst%/*}
-    re mkdir -p "$dstdir"
-    # Prefer localized templates, if they exist.
-    sname=${src%%.*}
-    if [ "$sname" != "$src" ]; then
-        sext=".${src#*.}"
-    else
-        unset sext
-    fi
-    language=${LANGUAGE:-$LANG}
-    for language in "${language%%:*}" "${language%%.*}" "${language%%_*}" ""; do
-        language=${language:+"-$language"}
-        test -f "$_APPLET_DIR/$sname$language$sext" || continue
-        if [ "$backup" = "1" ] && [ -f "$dst" ]; then
-            re mv "$dst" "$dst.old"
-        fi
-        re sed "$sedp" "$_APPLET_DIR/$sname$language$sext" > "$dst"
-        echo "Installed $_APPLET_DIR/$sname$language$sext in $dst"
-        return 0
-    done
-    die "Template file $src not found."
-}
-
 # Check if parameter is a command; `command -v` isn't allowed by POSIX
 is_command() {
     local fun
@@ -195,51 +154,6 @@ is_command() {
     for fun in "$@"; do
         command -v "$fun" >/dev/null || return $?
     done
-}
-
-kernel_variables() {
-    test -n "$kernel_variables" && return 0
-
-    # Exit if already evaluated
-    kernel_variables=1
-    # Extreme scenario: ltsp.loop="/path/to ltsp.vbox=1"
-    # We don't want that to set VBOX=1.
-    # Plan: replace spaces between quotes with \001,
-    # then split the parameters using space,
-    # then keep the ones that look like ltsp.var=value,
-    # and finally restore the spaces.
-    # TODO: should we add quotes when they don't exist?
-    # Note that it'll be hard when var=value" with "quotes" inside "it
-    eval "
-$(awk 'BEGIN { FS=""; }
-    {
-        s=$0   # source
-        d=""   # dest
-        inq=0  # in quote
-        split(s, chars, "")
-        for (i=1; i <= length(s); i++) {
-            if (inq && chars[i] == " ")
-                d=d "\001"
-            else {
-                d=d "" chars[i]
-                if (chars[i] == "\"")
-                    inq=!inq
-            }
-        }
-        split(d, vars, " ")
-        for (i=1; i in vars; i++) {
-            gsub("\001", " ", vars[i])
-            if (tolower(vars[i]) ~ /^ltsp.[a-zA-Z][-a-zA-Z0-9_]*=/) {
-                varvalue=substr(vars[i], 6)
-                eq=index(varvalue,"=")
-                var="LTSP_" toupper(substr(varvalue, 1, eq-1))
-                gsub("-", "_", var)
-                value=substr(varvalue, eq+1)
-                printf("%s=%s\n", var, value)
-            }
-        }
-    }
-    ' < /proc/cmdline)"
 }
 
 # Set _APPLET, _APPLET_DIR, _APPLET_FUNCTION and _SCRIPTS
@@ -267,30 +181,6 @@ locate_applet_scripts() {
             "/run/ltsp/$sub_dir/$_APPLET" \
             "/etc/ltsp/$sub_dir/$_APPLET"
     )
-}
-
-migrate_local_content() {
-    local old new local_content above_content below_content
-
-    old=$1
-    new=$2
-    test -f "$new" || die "migrate_local_content: $new not found"
-    test -f "$old" || return 0
-    local_content=$(re sed \
-        '/^### BEGIN LOCAL CONTENT/,/^### END LOCAL CONTENT/!d' "$old")
-    test -n "$local_content" || return 0
-    # https://stackoverflow.com/questions/15184358
-    above_content=$(re sed '/^### BEGIN LOCAL CONTENT/,$d' "$new" && echo EOF)
-    above_content="${above_content%
-EOF}"
-    test -n "$above_content" || die "No ### BEGIN LOCAL CONTENT in $new"
-    below_content=$(re sed '1,/^### END LOCAL CONTENT/d' "$new")
-    test -n "$below_content" || die "No ### END LOCAL CONTENT in $new"
-    re cat > "$new" <<EOF
-$above_content
-$local_content
-$below_content
-EOF
 }
 
 # Run a command. Exit if it failed.
@@ -422,15 +312,6 @@ source_scripts() {
     done 3<<EOF
 $scripts
 EOF
-}
-
-# Used by install_template
-textif() {
-    if [ "${1:-0}" != "0" ]; then
-        echo "$2"
-    else
-        echo "$3"
-    fi
 }
 
 # Show usage. _APPLET must be set. If $1 is set, exit with that code.
