Remove the ability to run via ltsp-applet symlinks

diff --git a/ltsp/ltsp b/ltsp/ltsp
--- a/ltsp/ltsp
+++ b/ltsp/ltsp
@@ -3,52 +3,52 @@
 # Copyright 2019 the LTSP team, see AUTHORS
 # SPDX-License-Identifier: GPL-3.0-or-later
 
+# This is the entry point for all ltsp applets.
 # Execution sequence:
-# This main() > source ltsp/* (and config/vendor overrides)
+# This main() > source common/ltsp/* (and config/vendor overrides)
 # > ltsp_cmdline() > ltsp/scriptname_main()s > source applet/* (and overrides)
 # > applet_cmdline() > applet/scriptname_main()s
 main() {
-    local scripts
-
     # Always stop on unhandled errors, http://fvue.nl/wiki/Bash:_Error_handling
     # Prefer `false || false` as it exits while `false && false` doesn't
     set -e
 
-    # If we're being sourced, $0 doesn't point to ltsp.sh, which means we
-    # can't locate applets etc. So the caller should manually set _SRC_DIR
-    # to source ltsp, and _APPLET to additionally source an applet.
-    if [ -n "$_SRC_DIR" ]; then
+    # Usually this script is called from a symlink like /usr/sbin/ltsp,
+    # so $0 points to the ltsp source directory. If that's not the case,
+    # assume we're sourced, and search for the source in /usr/share/ltsp.
+    _LTSP_DIR=$(re readlink -f "$0")
+    _LTSP_DIR=${_LTSP_DIR%/*}
+    if [ -x "$_LTSP_DIR/ltsp" ] && [ -d "$_LTSP_DIR/common" ]; then
+        unset _SOURCED
+        # Default to a sane umask for all files generated by applets
+        umask 0022
+    elif [ -x /usr/share/ltsp/ltsp.sh ] && [ -d /usr/share/ltsp/common ]; then
         _SOURCED=1
-        debug "ltsp.sh sourced by $0"
+        debug "ltsp sourced by $0"
         # Ignore all the caller command line parameters; they're not for us
         set --
-        # Derive e.g. _LTSP_APPLET="ltsp-kernel" and _APPLET="kernel"
-        if [ -n "$_APPLET" ]; then
-            _LTSP_APPLET="ltsp-$_APPLET"
-        else
-            _LTSP_APPLET="ltsp"
-            _APPLET="ltsp"
-        fi
+        _LTSP_DIR=/usr/share/ltsp
     else
-        _SRC_DIR=$(re readlink -f "$0")
-        _SRC_DIR=${_SRC_DIR%/*}
-        _LTSP_APPLET="${0##*/}"
-        _LTSP_APPLET="${_LTSP_APPLET%.sh}"
-        if [ "$_LTSP_APPLET" = "ltsp" ]; then
-            _APPLET=ltsp
-        else
-            _APPLET=${_LTSP_APPLET#ltsp-}
-        fi
+        die "Could not locate the ltsp directory"
     fi
-    scripts=$(list_applet_scripts "ltsp")
-    source_scripts "$scripts"
-    ltsp_cmdline "$scripts" "$@"
+    locate_applet_scripts "ltsp"
+    source_scripts "$_SCRIPTS"
+    test "$_SOURCED" = "1" || ltsp_cmdline "$@"
+}
+
+# Return "ltsp" or "ltsp $APPLET"
+ltsp_applet() {
+    if [ "$_APPLET" = ltsp ]; then
+        echo ltsp
+    else
+        echo "ltsp $APPLET"
+    fi
 }
 
 applet_usage() {
     local text
 
-    text=$(re man "$_LTSP_APPLET")
+    text=$(re man $(ltsp_applet))
     printf "Usage: %s\n\n%s\n\nOptions:\n%s\n" \
         "$(echo "$text" | sed -n '/^SYNOPSIS/,/^[^ ]/s/^\(       \|$\)//p')" \
         "$(echo "$text" | sed -n '/^DESCRIPTION/,/^[^ ]/s/^\(       \|$\)//p')" \
@@ -56,7 +56,7 @@ applet_usage() {
 }
 
 applet_version() {
-    echo "$_LTSP_APPLET $_VERSION"
+    echo "$(ltsp_applet) $_VERSION"
 }
 
 # True if can chroot into this dir
@@ -108,7 +108,7 @@ debug_shell() {
 # No need to pass a message if the failed command displays the error.
 die() {
     if [ $# -eq 0 ]; then
-        warn "Aborting ${_LTSP_APPLET:-LTSP}"
+        warn "Aborting $(ltsp_applet)"
     else
         warn "$@"
     fi
@@ -223,6 +223,36 @@ $(awk 'BEGIN { FS=""; }
     ' < /proc/cmdline)"
 }
 
+# Set _APPLET, _APPLET_DIR, _APPLET_FUNCTION and _SCRIPTS
+locate_applet_scripts() {
+    local search_dirs script
+
+    _APPLET=$1
+    shift
+    # Only allow client/* applets on ltsp-booted clients
+    if [ -d /run/ltsp/client ]; then
+        search_dirs="client server common"
+    else
+        search_dirs="server common"
+    fi
+    for sub_dir in $search_dirs; do
+        _APPLET_DIR="$_LTSP_DIR/$sub_dir/$_APPLET"
+        test -d "$_APPLET_DIR" && break
+    done
+    test -d "$_APPLET_DIR" || die "Could not locate LTSP applet: $_APPLET"
+    # All applets are required to have an entry function ${_APPLET}_cmdline
+    _APPLET_FUNCTION=$(echo "${_APPLET}_cmdline" | sed 's/[^[:alnum:]]/_/g')
+    # https://www.freedesktop.org/software/systemd/man/systemd.unit.html
+    # Drop-in files in /etc take precedence over those in /run
+    # which in turn take precedence over those in /usr.
+    _SCRIPTS=$(
+        test -f "/etc/ltsp/$_APPLET.conf" && echo "/etc/ltsp/$_APPLET.conf"
+        run_parts_list "$_APPLET_DIR" \
+            "/run/ltsp/$sub_dir/$_APPLET" \
+            "/etc/ltsp/$sub_dir/$_APPLET"
+    )
+}
+
 # Run a command. Exit if it failed.
 re() {
     rwr "$@" || die
@@ -276,7 +306,7 @@ rwr() {
 run_main_functions() {
     local scripts script
 
-    scripts="$1"; shift
+    scripts=$1; shift
     # 55-initrd.sh should be called as: initrd_main
     # <&3 is to allow scripts to use stdin instead of using the HEREDOC
     while read -r script <&3; do
@@ -337,24 +367,6 @@ run_parts_list() {
     | sort -r \
     | sort -t "$tab" -k 2,2 -u \
     | sed 's@[^\t]*\t[^\t]*\t@@'
-}
-
-list_applet_scripts() {
-    local applet script
-
-    applet=$1
-    shift
-    # One of the dirs must exist
-    if [ ! -d "$_SRC_DIR/applets/$applet" ] && [ ! -d "/run/ltsp/applets/$applet" ]; then
-        die "LTSP applet doesn't exist: $_SRC_DIR/applets/$applet"
-    fi
-    # https://www.freedesktop.org/software/systemd/man/systemd.unit.html
-    # Drop-in files in /etc take precedence over those in /run
-    # which in turn take precedence over those in /usr.
-    test -f "/etc/ltsp/$applet.conf" && echo "/etc/ltsp/$applet.conf"
-    run_parts_list "$_SRC_DIR/applets/$applet" \
-    "/run/ltsp/applets/$applet" \
-    "/etc/ltsp/applets/$applet"
 }
 
 source_scripts() {
